### ISSUE TITLE
Is there any example usage of adjustMediaQuery?

### ISSUE THREAD

**Issue by ChrisTucker2000** [stowball/mqGenie#12]
Hello. I'm trying to use this from within JavaScript, but all I can find about it is a very brief mention of how you can "use adjustMediaQuery". But how? If I try calling `adjustMediaQuery(query)`, I get a reference error - function not defined. If I try grabbing `window.mqGenie`, that's undefined too. I do have mqGenie running on the page, and it works fine to automatically adjust my CSS rules. But I can't figure out how I'm supposed to use it from within JavaScript.

**Comment by stowball** [comment]
If `window.mqGenie` is undefined, I'm highly dubious that mqGenie is indeed running on the page. Can you provide a test url?

**Comment by ChrisTucker2000** [comment]
Sorry, my mistake. I was trying to get it before the DOM had finished loading.
