### ISSUE TITLE
Toggling Firefox Responsive Design View doesn't update the media query widths

### ISSUE THREAD

**Issue by mm201** [stowball/mqGenie#9]
Responsive Design View is a new Firefox feature that emulates various device viewports and disables the scrollbar width. The thing is, toggling it doesn't refresh the page, so whatever the DOM is doing keeps on happening. mqGenie doesn't realize that scrollbars no longer have width, so it leaves the altered CSS in place, which leads to wrong layouts.

**Comment by stowball** [comment]
Yeah, it's an unfortunate issue, but not one that can be helped. Firefox doesn't fire any events when it goes in to Responsive Design View so there's no way of knowing. They also have other bugs in it, such as [MatchMedia not working](https://bugzilla.mozilla.org/show_bug.cgi?id=920379) and [it incorrectly calculating the width until DOMContentLoad fires](https://bugzilla.mozilla.org/show_bug.cgi?id=908568) :(

Related to that 2nd bug, window.onresize fires 2 events when it goes in to RWD View too, (one with normal scrollbar width and one without) so it's hard and heavy-handed to check and adjust all MQs just for this circumstance,

The only thing I can suggest is pretty much only working in Responsive Design View.

HTH
